FROM python:3.7-slim

# create app directory
WORKDIR /usr/src/app

# Install app dependencies
ADD requirements.txt ./

RUN pip install -r requirements.txt

LABEL version="1.0" description="Mock Server pip install Done" by="Frank.Chen" name="Mock Server base"