version: '3'

services:
  mongo:
    image: qa-gov.cn.lab/mongo
    container_name: mongo-db
    ports:
      - 27017:27017
    restart: always
    networks:
      - mock_net
    volumes:
      - ~/docker_volumes/mongo/data/db:/data/db

  mongo-express:
    links:
      - mongo
    image: qa-gov.cn.lab/mongo-express
    container_name: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    networks:
      - mock_net
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night

  mock-server:
    links:
      - mongo
    build: .
    ports:
      - "8080:8080"
    container_name: mock-server
    restart: always
    depends_on:
      - mongo
    networks:
      - mock_net
    environment:
      MOCK_CONFIG_MONGODB_SERVER: mongo

networks:
  mock_net:
    driver: bridge