# ------------------- Deployment ------------------- #
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: mock
  name: mock
  namespace: lab-02
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mock
  template:
    metadata:
      labels:
        k8s-app: mock
    spec:
      containers:
        - name: mock
          image: qa-gov.cn.lab/mock-server:$BUILD_NUMBER
          env:
            - name: MOCK_CONFIG_MONGODB_SERVER
              value: mock-mongo
            - name: MOCK_CONFIG_SITE_BASEURL
              value: /mock
            - name: MOCK_CONFIG_LOG_LEVEL
              value: DEBUG
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: mock-mongo
  name: mock-mongo
  namespace: lab-02
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: mock-mongo
  template:
    metadata:
      labels:
        k8s-app: mock-mongo
    spec:
      containers:
        - name: mock-mongo
          image: qa-gov.cn.lab/mongo:latest
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "100m"
          # volumeMounts:
          #   - name: ura-mongo-volume
          #     mountPath: /data/db
      # volumes:
      #   - name: ura-mongo-volume
      #     persistentVolumeClaim:
      #       claimName: mongo-data
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: mock-mongo-express
  name: mock-mongo-express
  namespace: lab-02
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: mock-mongo-express
  template:
    metadata:
      labels:
        k8s-app: mock-mongo-express
    spec:
      containers:
        - name: mock-mongo-express
          image: qa-gov.cn.lab/mongo-express:latest
          env:
            # - name: ME_CONFIG_BASICAUTH_USERNAME
            #   value: mock
            # - name: ME_CONFIG_BASICAUTH_PASSWORD
            #   value: $ME_PASSWORD
            - name: ME_CONFIG_MONGODB_SERVER
              value: mock-mongo
            - name: ME_CONFIG_SITE_BASEURL
              value: /mongo/mock
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
# ------------------- Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: mock
  name: mock
  namespace: lab-02
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    k8s-app: mock
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: mock-mongo
  name: mock-mongo
  namespace: lab-02
spec:
  # externalTrafficPolicy: Local
  # type: LoadBalancer
  type: NodePort
  ports:
    - name: mongo-db
      port: 27017
      targetPort: 27017
      nodePort: 30017
  selector:
    k8s-app: mock-mongo
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: mock-mongo-express
  name: mock-mongo-express
  namespace: lab-02
spec:
  ports:
    - name: web
      port: 8081
      targetPort: 8081
  selector:
    k8s-app: mock-mongo-express
---
# ------------------- Ingress ------------------- #
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mock
  namespace: lab-02
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: qa-gov.cn.lab
      http:
        paths:
          - backend:
              serviceName: mock
              servicePort: 8080
            path: /mock
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mock-mongo-express
  namespace: lab-02
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: qa-gov.cn.lab
      http:
        paths:
          - backend:
              serviceName: mock-mongo-express
              servicePort: 8081
            path: /mongo/mock
