apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: mock-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: mock
  updatePolicy:
    updateMode: "Auto"